### ISSUE TITLE
active_sensors.py? 

### ISSUE THREAD

**Issue by glooker** [publicsensors/MicrocontrollerKits#31]
Having trouble locating active_sensors.py. thanks

**Comment by seastate** [comment]
@glooker, thanks for the query.

We are in the process of implementing a new version of our software (and webpages).

active_sensors.py and the other code from our original version is now in the basic_v0.1 branch.

If this is not familiar, the branch is chosen on the github page through the menu at the top left of a code page.

From a terminal, use a command like

git checkout basic_v0.1

You should then see the original codes, including active_sensors.py in the Sensors subdirectory.

**Comment by seastate** [comment]
@glooker, thanks for the query.

We are in the process of implementing a new version of our software (and webpages).

active_sensors.py and the other code from our original version is now in the basic_v0.1 branch.

If this is not familiar, the branch is chosen on the github page through the menu at the top left of a code page.

From a terminal, use a command like

git checkout basic_v0.1

You should then see the original codes, including active_sensors.py in the Sensors subdirectory.
